// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgLJQbdozsb8HLQDnkPAbfORxyvmJQHJM',
    appId: '1:240742849209:web:a19f63e188909641e39968',
    messagingSenderId: '240742849209',
    projectId: 'gymkoda',
    authDomain: 'gymkoda.firebaseapp.com',
    storageBucket: 'gymkoda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE7_sXGcqALgblJAZqjRg0Wc1BsRhps9k',
    appId: '1:240742849209:ios:534dab5c45c28f10e39968',
    messagingSenderId: '240742849209',
    projectId: 'gymkoda',
    storageBucket: 'gymkoda.firebasestorage.app',
    androidClientId: '240742849209-hf9t377su3uhsfhes993ddbbkd4vfgls.apps.googleusercontent.com',
    iosClientId: '240742849209-qjs2c0jh5415qsc0b7lm2e0r3hapdnh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE7_sXGcqALgblJAZqjRg0Wc1BsRhps9k',
    appId: '1:240742849209:ios:534dab5c45c28f10e39968',
    messagingSenderId: '240742849209',
    projectId: 'gymkoda',
    storageBucket: 'gymkoda.firebasestorage.app',
    androidClientId: '240742849209-hf9t377su3uhsfhes993ddbbkd4vfgls.apps.googleusercontent.com',
    iosClientId: '240742849209-qjs2c0jh5415qsc0b7lm2e0r3hapdnh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgLJQbdozsb8HLQDnkPAbfORxyvmJQHJM',
    appId: '1:240742849209:web:66f34217c9200810e39968',
    messagingSenderId: '240742849209',
    projectId: 'gymkoda',
    authDomain: 'gymkoda.firebaseapp.com',
    storageBucket: 'gymkoda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJeoaG7RVFRpsvwiq5ajwLHm-dN__jg3s',
    appId: '1:240742849209:android:275758c042e4decae39968',
    messagingSenderId: '240742849209',
    projectId: 'gymkoda',
    storageBucket: 'gymkoda.firebasestorage.app',
  );

}